# set the base image. Since we're running 
# a Python application a Python base image is used
FROM python:3.8
# set a key-value label for the Docker image
LABEL maintainer="Mitesh"
WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 3111
#RUN "python init_db.py"
CMD [ "python", "./init_db.py" ]
CMD [ "python", "./app.py" ]
