namespace:
  name: sandbox
service:
  port: 7111
 
image:
  pullPolicy: Always

replicaCount: 5

resources:
  requestsMemory:"128Mi"
  requestsCPU:"350m"
  limitMemory:"256Mi"
  limitCPU:"500m"

  	
